package com.example.demo.config;

public enum BenefitOfOjt {
    HAVE_A_CHANCE_TO_WORK_IN_REAL_WORKING_ENVIROMENT,
    KNOWLEDGE_AT_SCHOOL_IS_CONSOLIDATED_AND_PRACTICE,
    HAVE_RIGHT_KNOWLEDGE_ABOUT_FUTURE_CAREER,
    APPROACHED_PROFESSIONAL_SKILLS_AND_PRACTICES
}
