import {
  Breadcrumbs,
  Cards,
  Carousels,
  Collapses,
  Dropdowns,
  Forms,
  Jumbotrons,
  ListGroups,
  Navbars,
  Navs,
  Paginations,
  Popovers,
  ProgressBar,
  Switches,
  Tables,
  Tabs,
  Tooltips,
  Test,
  Excels,
  ScheduleParameters,
  Company,
  ChangePassword,
  Invitation,
  Invitation_Detail,
  Invitation_Create,
  Ojt_Registration,
  CV,
  student_list,
  business_list,
  Specialized,
  Specialized_Create,
  Specialized_Update,
  Skill,
  Skill_Create,
  Skill_Update,
  ManageAccount,
  Account_Create,
  User_Student,
  User_Student_Create,
  User_Business,
  User_Business_Create,
  Job_Post_List,
  Job_Post_List_HR,
  InformMessage,
  Create_InformMessage,
  Report,
  Hr_Students,
  Hr_Students_Detail,
  Hr_Task,
  Hr_Task_Create,
  Hr_Task_Detail,
  Hr_Task_Update,
  Feedback,
  BusinessProposed,
  BusinessProposed_Detail,
  BusinessProposed_Update,
  SiteAdmin,
  AnswerStatistics,
  SiteHr,
  SiteSupervisor,
  Question,
  Add_Question,
  Update_Question,
  Log

} from './Base';

import { ButtonDropdowns, ButtonGroups, Buttons, BrandButtons } from './Buttons';
import Charts from './Charts';
import Dashboard from './Dashboard';
import { CoreUIIcons, Flags, FontAwesome, SimpleLineIcons } from './Icons';
import { Alerts, Badges, Modals } from './Notifications';
import { Login, Page404, Page500, ForgotPassword, ResetPassword } from './Pages';
import { Colors, Typography } from './Theme';
import Widgets from './Widgets';
import Official_List from "./Official_List/Official_List";
import Details_Task from "./Details_Task/Details_Task";
import Job_Post from "./Job_Post/Job_Post";
import InformMessage_Detail from "./InformMessage/InformMessage_Detail";
import Feedback_Detail from "./Feedback/Feedback_Detail";
import Report_Detail from "./Report/Report_Detail";
import Create_Report from "./Report/Create_Report";
import Update_Report from "./Report/Update_Report";

export {
  Badges,
  Typography,
  Colors,
  CoreUIIcons,
  Page404,
  Page500,
  ForgotPassword,
  ResetPassword,
  Login,
  Modals,
  Alerts,
  Flags,
  SimpleLineIcons,
  FontAwesome,
  ButtonDropdowns,
  ButtonGroups,
  BrandButtons,
  Buttons,
  Tooltips,
  Tabs,
  Tables,
  Charts,
  Dashboard,
  Widgets,
  Jumbotrons,
  Switches,
  ProgressBar,
  Popovers,
  Navs,
  Navbars,
  ListGroups,
  Forms,
  Dropdowns,
  Collapses,
  Carousels,
  Cards,
  Breadcrumbs,
  Paginations,
  Test,
  Excels,
  ScheduleParameters,
  Company,
  ChangePassword,
  Invitation,
  Invitation_Detail,
  Invitation_Create,
  Ojt_Registration,
  CV,
  student_list,
  business_list,
  Official_List,
  Details_Task,
  Job_Post,
  Specialized,
  Specialized_Create,
  Specialized_Update,
  Skill,
  Skill_Create,
  Skill_Update,
  ManageAccount,
  Account_Create,
  User_Student,
  User_Student_Create,
  User_Business,
  User_Business_Create,
  Job_Post_List,
  Job_Post_List_HR,
  InformMessage,
  Create_InformMessage,
  InformMessage_Detail,
  Report,
  Report_Detail,
  Create_Report,
  Update_Report,
  Hr_Students,
  Hr_Students_Detail,
  Hr_Task,
  Hr_Task_Create,
  Hr_Task_Detail,
  Hr_Task_Update,
  Feedback,
  Feedback_Detail,
  BusinessProposed,
  BusinessProposed_Detail,
  BusinessProposed_Update,
  SiteAdmin,
  AnswerStatistics,
  SiteHr,
  SiteSupervisor,
  Question,
  Add_Question,
  Update_Question,
  Log
};

